name: Analyze Bundle

on:
  pull_request:
  push:
    branches:
      - main 
      - master # change this if your default branch is named differently
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code 
        uses: actions/checkout@v2
    
        

     
